# Generated by Django 2.2.6 on 2019-11-02 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='Unknown', max_length=128)),
                ('photo', models.FileField(default=None, upload_to='uploads', verbose_name='filepath')),
                ('date_posted', models.DateTimeField(auto_now=True, verbose_name='Upload date')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='Unknown', max_length=128)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshare.Post')),
            ],
        ),
    ]
