# Generated by Django 2.2.6 on 2019-11-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pet_name',
            field=models.CharField(default='Unknown Pet', max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='pet_type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Cat'), (2, 'Dog'), (3, 'Guinea Pig'), (4, 'Hamster'), (5, 'Poring'), (6, 'Dragon')], default=0, max_length=24),
        ),
    ]
