# Generated by Django 2.2.6 on 2019-11-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshare', '0002_auto_20191102_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pet_type',
            field=models.IntegerField(choices=[(0, 'Other'), (1, 'Cat'), (2, 'Dog'), (3, 'Guinea Pig'), (4, 'Hamster'), (5, 'Poring'), (6, 'Dragon')], default=0),
        ),
    ]
