# Generated by Django 2.2.6 on 2019-11-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshare', '0003_auto_20191102_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FileField(default=None, upload_to='petshare/static/uploads', verbose_name='filepath'),
        ),
    ]
