# Generated by Django 2.2.6 on 2019-11-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshare', '0004_auto_20191102_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='nickname',
            field=models.CharField(default='Unknown', help_text='Your nickname', max_length=128, unique=True),
        ),
    ]
